# fly.toml app configuration file generated for fast-zero-restless-leaf-1210 on 2024-07-30T21:37:36-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fast-zero-restless-leaf-1210'
primary_region = 'gru'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[deploy]
  console_command = "alembic upgrade head"

[[vm]]
  size = 'shared-cpu-1x'
